[package]
name = "rex-s3"
version.workspace = true
edition.workspace = true

[dependencies]
rex-common = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-config = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
