[package]
name = "rex-mssql"
version.workspace = true
edition.workspace = true
description = "SQL Server (MSSQL) protocol implementation for REX"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
rex-common.workspace = true
tiberius = { workspace = true }
async-trait.workspace = true
